### ISSUE TITLE
Fixnum Issues with latest Ruby version

### ISSUE THREAD

**Issue by srikanthAnuguAmount** [citizen428/shenanigans#4]
Fixnum Issues with latest Ruby version (since 2.4 version, fixnum is gone)

**Comment by citizen428** [comment]
The only mention of `Fixnum` in the entire codebase is in a comment on in `lib/shenanigans/hash/has_shape_pred.rb`.

The one extension method previously defined on `Fixnum` was moved to `Integer` in 614450ed9d2b74d1e9163e97896aa3e5a6d79656.

**Comment by citizen428** [comment]
Ah, I got it now, I forgot to change on `require` line.

**Comment by citizen428** [comment]
Fixed and released a new gem version now.
